language:
  python
python:
- "3.8"
- "3.9"
- "3.10"
- "3.11"
# install dependencies
install:
- pip install -r requirements.txt
- pip install codecov pdoc3 pytest pytest-cov
# run tests
script:
- pytest
- coverage run -m pytest
after_success:
  - codecov